import:
  - ~/.config/alacritty/one-dark.yml

font:
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  size: 12
