set virtualedit=block
set whichwrap=<,>,[,]

set ignorecase
set smartcase

set number
set scrolloff=4
set signcolumn=number

set tabstop=4
set shiftwidth=4
set expandtab

set breakindent
set linebreak

set clipboard=unnamedplus

command! W w
command! Q q
command! WQ wq
command! Wq wq
command! QA qa
command! Qa qa

let mapleader = ";"
nmap ' <Leader>

nnoremap n nzz
nnoremap N Nzz
nnoremap { {zz
nnoremap } }zz

nnoremap <Leader>d "_d
vnoremap <Leader>d "_d
nnoremap <Leader>c "_c
vnoremap <Leader>c "_c
nnoremap <Leader>x "_x
vnoremap <Leader>x "_x

nnoremap q: <Nop>
vnoremap q: <Nop>

nnoremap ( <Nop>
vnoremap ( <Nop>
nnoremap ) <Nop>
vnoremap ) <Nop>

nnoremap <C-e> <Nop>
vnoremap <C-e> <Nop>
nnoremap <C-d> <Nop>
vnoremap <C-d> <Nop>
nnoremap <C-f> <Nop>
vnoremap <C-f> <Nop>
nnoremap <C-y> <Nop>
vnoremap <C-y> <Nop>
nnoremap <C-u> <Nop>
vnoremap <C-u> <Nop>
nnoremap <C-b> <Nop>
vnoremap <C-b> <Nop>
nnoremap H <Nop>
vnoremap H <Nop>
nnoremap M <Nop>
vnoremap M <Nop>
nnoremap L <Nop>
vnoremap L <Nop>

nnoremap <F1> <Nop>
vnoremap <F1> <Nop>
